- name: ping module
  hosts: vinay
  become : yes
  serial : 2
  tasks:
  - name : ping 
    ping: 
  - name : installing nginx
    package :
      name : nginx
      state : present
  - name : started
    service :
      name : nginx
      state : started
      
